### ISSUE TITLE
Exception when trying to run the sample

### ISSUE THREAD

**Issue by mythjuha** [RusticiSoftware/scormcloud-api-v2-client-net#12]
We're looking into using ScormCloud as our Scorm solution for our education center. Our software has recently been updated to .Net 5.0.

When trying to run tests to see if and scormcloud is compatible I already end up running into problems with the sample on the main page.

Specifically the line:
```
StringResultSchema tokenResult = applicationManagementApi.CreateToken(tokenRequest);
```
Throws the following exception:
```
System.MissingMethodException: 'Method not found: 'RestSharp.IRestRequest RestSharp.RestRequest.AddFile(System.String, System.Action`1<System.IO.Stream>, System.String, System.String)'.'
```

**Comment by mjschuetze102** [comment]
This problem has been fixed in the latest release (#14) and is now publicly available after fixing a problem with our nuspec file (#17). RestSharp is now at 106.12.0 and support for .NET 5.0 has been added.
