### ISSUE TITLE
System.Net.Http Security Risks

### ISSUE THREAD

**Issue by raymondht** [RusticiSoftware/scormcloud-api-v2-client-net#28]
Hi team,

Do you have any plan upgrading System.Net.Http in your package? Our system detects multiple security risks introduced by the version 
4.3.0 of the System.Net.Http through your package.

![image](https://github.com/RusticiSoftware/scormcloud-api-v2-client-net/assets/25966551/c5fe9845-4ea9-4041-bc15-f2a2d56e9f11)

Looking forward to hearing from you.

**Comment by mjschuetze102** [comment]
Hello!

It looks like `JsonSubTypes` v1.4.0 added explicit support for .NET Standard 2.0. Versions prior to that required `NETStandard.Library` which provided the vulnerability you've listed above. Updating JsonSubTypes to at least v1.4.0 should fix the security vulnerability. I did a smoke test updating to JsonSubTypes v2.0.1 and nothing seemed to break

We will update the minimum version of JsonSubTypes in our next release. Date TBD. Until then, downloading a more recent version of JsonSubTypes should fix the security concern on your end

Let me know if you have any other questions

**Comment by cojohnson1999** [comment]
Hi there!

Thanks for your patience as we worked to resolve this.  Release [4.0.0](https://github.com/RusticiSoftware/scormcloud-api-v2-client-net/pull/29) updated `JsonSubTypes` to v1.4.0, which should fix the security issues you were having.

I'm closing this issue as completed now.  Please let us know if anything else comes up!
