### ISSUE TITLE
Best practice initialization examples/suggestions for APIv2?

### ISSUE THREAD

**Issue by cemerson** [RusticiSoftware/scormcloud-api-v2-client-net#6]
Hey, guys. 

Previously, with APIv1, I would initialize things via something like the below code. However w/the APIv2 there seem to be more "init" things going on which may just require more lines of code per call (for permission schema, token generation etc). I will be trying to figure out the best way on my own as I go but if anyone has any examples or best-practice suggestions on how to initialize the APIv2 library before each call please let me know or point me to them. Thank you in advance. 

`// Base init stuff`
`ScormCloud.Configuration = new RusticiSoftware.HostedEngine.Client.Configuration(`
                      `                scormCloudURL,`
`                scormCloudAppID,`
`                scormSecurityKey,`
`                scormCloudOrigin);`

`// My API method call(s)`
`ScormCloud.DebugService.CloudPing();`

**Comment by neil-russell** [comment]
We just configure the default instance once during startup, no need to initialize before each call.  
```
Com.RusticiSoftware.Cloud.V2.Client.Configuration.Default.Username = configuration["ScormCloud:AppId"];
Com.RusticiSoftware.Cloud.V2.Client.Configuration.Default.Password = configuration["ScormCloud:SecretKey"];  
```
