### ISSUE TITLE
How to get/read MessageSchema response?

### ISSUE THREAD

**Issue by cemerson** [RusticiSoftware/scormcloud-api-v2-client-net#7]
Is there a way to get/read the MessageSchema response from calls? For example, putLearnerTags according to the Scorm Cloud APIv2 documentation should return JSON w/MessageSchema result but in this .NET library PutLearnerTags returns void. Thank you in advance!

`                LearnerApi apiInstance = new LearnerApi();                `
`                apiInstance = new LearnerApi();`
`                apiInstance.PutLearnerTags(userEmail, tagsForUser);                `

**Comment by mjschuetze102** [comment]
Closing as the new update is now publicly available after fixing a problem with our nuspec file (#17).
